---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        servicePort: "80"
    spec:
      containers:
        - name: web
          image: nginx:1.7.9
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    zookeeper/path: "/aurora/job/role/prod/service/"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
