---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zk
          image: netflixoss/exhibitor:1.5.2
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - name: port-2181
      port: 2181
    - name: port-2888
      port: 2888
    - name: port-3888
      port: 3888
  selector:
    app: zookeeper
