---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk-announser
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zk-announser
    spec:
      containers:
        - name: announser
          image: quay.io/mad01/k8s-zk-announser:f594ab1d30506a75c8e035652f45773145f88944
          command:
            - "./k8s-zk-announser"
          args:
            - "-zookeeper.addr=zookeeper"
